### ISSUE TITLE
Question: how to use the 'combo-box widget?

### ISSUE THREAD

**Issue by kssytsrk** [borodust/bodge-ui#17]
Hi, I am aware this library is not yet production quality, but it seems like a nice project and I like playing around with it. The examples in this repo and the [bodge-ui-window](https://github.com/borodust/bodge-ui-window) repo demonstrate how `radio-group`, `text-edit` and `button` widgets work very nicely, but there's no examples of `combo-box` usage. 

What I tried: I copied the code from the [drawing example](https://github.com/borodust/bodge-ui-window/blob/master/examples/drawing-example.org) and changed the definition of `main-panel` to this:

```common-lisp
(defpanel (main-panel
           (:title "Control Panel")
           (:origin 25 355)
           (:width 200) (:height 220)
           (:options :movable :resizable
                     :minimizable :scrollable
                     :closable))
  (horizontal-layout
   (combo-box :values '("item1" "item2"))
   (button :label "Refresh" :expandable nil :width 70 :on-click #'refresh-text)))
```

I expected to have a combo-box with values "item1" and "item2", but instead (after I run the function that opens the window) I got: 

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION BODGE-UI:CALCULATE-TEXT-WIDTH (1)>
when called with arguments
  (#<BODGE-CANVAS-UI::UI-RENDERER {10024D8C33}> "item1").
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
```

I also tried making a combo-box with nothing passed to the `:values` slot at all and got a similar result. 

So, the question: how do I make a combo-box, am I missing something? Or is the combo-box not really finished yet? (if it's not, would love some pointers on how to use `list-select`, because if I'm not mistaken it's the closest thing to a combo-box)

**Comment by borodust** [comment]
Yeah, `bodge-ui` is kinda alpha quality. It still is an experiment how nuklear can be lispified.
Fix for `combo-box` is in https://github.com/borodust/bodge-ui/commit/9d457d1ec02bcc438efbc260b0943ec74d9e9a51 
Looks like default nuklear renderer is borked anyway - `combo-box` drop downs are not correctly displayed due to text  width calculation bug I suspect (could be just HiDPI issue). NanoVG-based renderer works fine though (it is hidpi aware):
```lisp
(ql:quickload :bodge-ui-window/examples) (bodge-ui-window.example.basic:run)
``` 
Add `combo-box` into [basic example](https://github.com/borodust/bodge-ui-window/blob/master/examples/basic-example.org), should work fine.

**Comment by borodust** [comment]
P.S.: If you have no plans to code dive into this mess of a project, I recommend avoiding it. I'm [super focused on different projects](https://github.com/borodust/borodust/tree/a4bee14e9c0a39a1b92d0bfa1c1aed205cd1ce3b) atm (on the underlying tech, basically - `:claw`) and have no near future plans to extend `bodge-ui`. But if for some reason you are not discouraged yet, I surely can help with code dissection :) Ping me on `#cl-bodge` channel at `irc.freenode.net` or `#common-lisp` at Lisp Discord.

**Comment by kssytsrk** [comment]
> Looks like default nuklear renderer is borked anyway - combo-box drop downs are not correctly displayed due to text width calculation bug I suspect (could be just HiDPI issue). NanoVG-based renderer works fine though (it is hidpi aware)

Well, with SBCL 2.0.8 and Artix Linux I get 

```
The alien function "nvgCreateGL2" is undefined.
   [Condition of type SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR]
```

Do I perhaps need to install something else before running `(ql:quickload :bodge-ui-window/examples)`?

> If you have no plans to code dive into this mess of a project, I recommend avoiding it. I'm super focused on different projects atm (on the underlying tech, basically - :claw) and have no near future plans to extend bodge-ui.

Ah, I see. Is plain `bodge-nuclear` more mature?

> But if for some reason you are not discouraged yet, I surely can help with code dissection :) Ping me on #cl-bodge channel at irc.freenode.net or #common-lisp at Lisp Discord.

Thank you! I'll probably put bodge-ui into my "projects to look into later" org file as the idea is cool but right now I'm just trying to find some small/minimal gui toolkit to finish one of my own projects :)

**Comment by borodust** [comment]
> Well, with SBCL 2.0.8 and Artix Linux I get

Try with pristine image (restart SBCL, and start from scratch). Before loading anything, do
```lisp
(pushnew :bodge-gl2 *features*)
``` 
Then load `bodge-ui-examples` and try again.
If that didn't work, maybe install bodge dist - it has more up-to-date versions of bodge stuff:
```lisp
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt")
```
Then restart and try again.
As for the error - it tries to use OpenGL2 backend (although default is OpenGL3) and fails to do so. I guess, because wrong shared library is getting loaded.

> Ah, I see. Is plain bodge-nuclear more mature?

You can say so. `bodge-nuklear` is direct low-level bindings to `Nuklear` autogenerated from its header - no fancy lispifcation. Using bindings directly is a huge PITA - Nuklear error handling is based on asserts, and if you do something wrong, even the little things, it would crash your image with native assert. Meaning, you would restart things again and again. Not very lispy approach to development :)

> I'm just trying to find some small/minimal gui toolkit to finish one of my own projects

Not very small libraries, but if you didn't look yet glimpse at [McCLIM](https://common-lisp.net/project/mcclim/), [Alloy](https://github.com/Shirakumo/alloy), [IUP](https://github.com/lispnik/iup), [qtools](https://github.com/Shinmera/qtools), [LTK](https://github.com/herth/ltk), [EQL5](https://gitlab.com/eql/EQL5/-/wikis/home).

Alloy in particular might suit you well.

**Comment by kssytsrk** [comment]
Still doesn't work, here's what I've tried:
1. restarting, then quickloading and running
2. restarting, pushing opengl-2 into *features* and then quickloading and running
3. restarting, installing the dist, pushing opengl-2 into *features* and then quickloading and running
The error of text width calculation persists :(

> You can say so. bodge-nuklear is direct low-level bindings to Nuklear autogenerated from its header - no fancy lispifcation. Using bindings directly is a huge PITA - Nuklear error handling is based on asserts, and if you do something wrong, even the little things, it would crash your image with native assert. Meaning, you would restart things again and again. Not very lispy approach to development :)

Hmm, so this project has a good reason to exist indeed :)

> Not very small libraries, but if you didn't look yet glimpse at McCLIM, Alloy, IUP, qtools, LTK, EQL5.
> Alloy in particular might suit you well.

Thanks for the list! I've looked into McCLIM and didn't like it much. Alloy seems nice but a big part of it is undocumented (and not very self-explanatory) and the examples didn't render well. I was far too lazy to look for causes of that in my setup or in the lib's source code so I just ditched the thought of having any ui widgets altogether and stuck with lispbuilder-sdl (my main goal was mostly just drawing pixels to the screen anyway), haha.

**Comment by borodust** [comment]
> Still doesn't work

🤔
* Ensure you don't have anything bodge-related in `~/quicklisp/local-projects/` except for `bodge-ui` with the combo-box fix
* In clean image (paste into freshly restarted SBCL's REPL):
```common-lisp
(ql:quickload :bodge-ui-window)

(cl:defpackage :%bodge-ui-window.example.basic
  (:use :cl :bodge-ui :bodge-host)
  (:export #:run))

(cl:in-package :%bodge-ui-window.example.basic)

(defpanel (main-panel
            (:title "Hello Bodge UI")
            (:origin 200 50)
            (:width 400) (:height 400)
            (:options :movable :resizable
                      :minimizable :scrollable
                      :closable))
  (label :text "Nested:")
  (horizontal-layout
   (radio-group
    (radio :label "Option 1")
    (radio :label "Option 2" :activated t))
   (vertical-layout
    (check-box :label "Check 1" :width 100)
    (check-box :label "Check 2"))
   (vertical-layout
    (label :text "Awesomely" :align :left)
    (label :text "Stacked" :align :centered)
    (label :text "Labels" :align :right)))
  (label :text "Expand by width:")
  (horizontal-layout
   (button :label "Dynamic")
   (button :label "Min-Width" :width 80)
   (button :label "Fixed-Width" :expandable nil :width 100))
  (label :text "Expand by ratio:")
  (horizontal-layout
   (button :label "1.0" :expand-ratio 1.0)
   (button :label "0.75" :expand-ratio 0.75)
   (button :label "0.5" :expand-ratio 0.5))
  (label :text "Rest:")
  (button :label "Top-Level Button")
  (combo-box :values '("item1" "item2")))

(defparameter *window-width* 800)
(defparameter *window-height* 600)

;; Define main window
(defclass main-window (bodge-ui-window:ui-window) ()
  (:default-initargs
   :title "Bodge UI Window Example"
   :width *window-width*
   :height *window-height*
   :panels '(main-panel)
   :floating t
   :opengl-version '(3 3)))

(defun run ()
  (bodge-host:open-window (make-instance 'main-window)))
```
* Run it with
```common-lisp
(%bodge-ui-window.example.basic:run)
```

If that didn't work, let's continue in [Lisp discord](https://discord.gg/hhk46CE) or at [irc.freenode.net](https://webchat.freenode.net/?channel=#lispgames) chats (look for `borodust`).

**Comment by borodust** [comment]
BTW, are you running that on `x86_64` arch and SBCL is `x86_64` too?

**Comment by kssytsrk** [comment]
> BTW, are you running that on x86_64 arch and SBCL is x86_64 too?

Yes. Thank you, after following these exact steps it worked :)
