### ISSUE TITLE
Add :NO-INPUT, or add a T case for UPDATE-PANEL-OPTIONS

### ISSUE THREAD

**Issue by kchanqvq** [borodust/bodge-ui#18]
Hi, I tried to use `:NO-INPUT` for panel option but it got eaten by the `CASE` in
`UPDATE-PANEL-OPTIONS`, although it's readily available from the CFFI
bitfield type `PANEL-FLAGS`. Could you either add this option, or just add a clause
`(T (push opt updated-opts))`?

**Comment by borodust** [comment]
Fixed in https://github.com/borodust/bodge-ui/commit/94fb37de3dcfe18f97945a29c70f451ebfb6966b
Exposed as `:inputless`
